version: "4.12.0"

services:
  database:
    container_name: vial-backend-b
    image: postgres:latest
    environment:
      POSTGRES_USER: vial
      POSTGRES_PASSWORD: vial
      POSTGRES_DB: vial
    ports:
      - 5432:5432

  backend:
    container_name: vial-backend-b-api
    image: node:18.15.0
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    command: npm run dev
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules
    env_file:
      - backend/.env
    depends_on:
      - database
    ports:
      - "8080:8080"


  frontend:
    container_name: vial-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    volumes:
      - ./frontend:/usr/app
      - /usr/app/node_modules
    env_file:
      - frontend/.env
    ports:
      - "5173:5173"

volumes:
  db_data: